name: 'swedbank_demo'
version: '1.0.0'
config-version: 2

profile: 'swedbank_demo'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  swedbank_demo:
    01_source_systems:
      +schema: source_systems
      +materialized: view
    02_transformation_layer:
      +schema: transformation_layer
      +materialized: view
    03_kri_report_layer:
      +schema: kri_report_layer
      +materialized: table
    04_governance_metadata:
      +schema: governance_metadata
      +materialized: view
